server:
    port: 8090

spring:
    kafka:
        bootstrap-servers: 192.168.99.100:9092

app:
  topic:
    clientmessage: clientmessage.t
    servermessage: servermessage.t

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG